project:
  type: website
  output-dir: _site
  resources:
    - notebooks_amt/PotterAttributionExample.ttl
    - notebooks_amt/amt-python.ipynb
    - img/CC_SemanticLOD_Logo.png
    - unicorn/unicorn_arno_sites.png

website:
  title: "SPARQLing Archaeology"
  navbar:
    left:
      - text: "Introduction"
        href: index.qmd
      - text: "Jupyter Notebooks: LOD"
        menu:
          - text: "Wikidata Ogham Site Diagrams"
            href: notebooks_lod/wikidata-ogham-sites-live.qmd
          - text: "Wikidata Ogham Sites Leaflet Map"
            href: notebooks_lod/wikidata-ogham-sites-map-live.qmd
          - text: "NFDI4Objects KG Ogham Sites Diagrams"
            href: notebooks_lod/n4okg-ogham-sites-county-live.qmd
          - text: "NFDI4Objects KG Ogham Sites Leaflet Map"
            href: notebooks_lod/n4okg-ogham-sites-map-live.qmd
          - text: "NFDI4Objects KG Samian Production centres"
            href: notebooks_lod/n4okg-samian-production-centres-live.qmd
          - text: "NFDI4Objects KG Samian Discovery sites & Pleiades"
            href: notebooks_lod/n4okg-samian-discovery-sites-live.qmd
          - text: "NFDI4Objects KG Samian Potter activity"
            href: notebooks_lod/n4okg-samian-potter-activity-live.qmd
          - text: "Local TTL-File Campanian Ignimbrite Sites"
            href: notebooks_lod/local_ttl-campanian-ignimbrite-sites-live.qmd
      - text: "Jupyter Notebooks: AMT"
        menu:
          - text: "Academic Meta Tool - Potter Attribution Example"
            href: notebooks_amt/amt-live.qmd
      - text: "SPARQLing Unicorn QGIS Plugin"
        menu:
          - text: "QGIS Plugin: SPARQL query"
            href: unicorn/sparql-queries.qmd

execute:
  freeze: auto
