project:
  type: website
  output-dir: _site
  resources:
    - notebooks_amt/PotterAttributionExample.ttl
    - notebooks_amt/amt-python.ipynb
    - img/CC_SemanticLOD_Logo.png
    - unicorn/unicorn_arno_sites.png

website:
  title: "Knowledge Graphs in Action"
  navbar:
    left:
      - text: "Skript"
        href: index.qmd
      - text: "Jupyter Notebooks Linked Data"
        menu:
          - text: "Wikidata Ogham Site Diagrams"
            href: notebooks_lod/wikidata-ogham-sites-live.qmd
          - text: "Wikidata Ogham Sites Leaflet Map"
            href: notebooks_lod/wikidata-ogham-sites-map-live.qmd
      - text: "Jupyter Notebooks Academic Meta Tool"
        menu:
          - text: "AMT – Academic Meta Tool (interaktiv)"
            href: notebooks_amt/amt-live.qmd
      - text: "SPARQLing Unicorn"
        menu:
          - text: "QGIS Plugin SPARQL query"
            href: unicorn/sparql-queries.qmd

execute:
  freeze: auto
